### ISSUE TITLE
I can't get the RTSP stream to work

### ISSUE THREAD

**Issue by UberWagen** [thehapyone/NanoCamera#5]
I'd like to stream my Jetson Nano's CSI camera over my network. The nanocamera program works and has very high quality feedback, but I'm having trouble with the RTSP example.

If I execute the RTSP example where I've changed my rtsp_location to the ip of my Jetson Nano, I get the following error:

`<....>line 25, in <module>
    cv2.imshow("Video Frame", frame)
cv2.error: OpenCV(4.1.1) /home/nvidia/host/build_opencv/nv_opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'`

I'm not really sure what's happening with the opencv error. Very general. 

Any pointers? I'm also completely new to RTSP streaming. Is there anything outside of the RTSP example I need to do other than changing

**Comment by thehapyone** [comment]
@UberWagen The nano camera program works for receiving RTSP camera stream but not for creating one. You need to have a valid RTSP camera stream. You can use gsteamer or even VLC to create a video stream. 

The OpenCV error is because the image input doesn't not have any shape I.e no valid image data provided.
